# Generated by Django 4.2.6 on 2024-02-28 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_app', '0007_rename_tag_hashtag_rename_tags_post_hashtag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poststatistics',
            name='view_count',
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='posts', to='social_media_app.category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='poststatistics',
            name='comment_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='poststatistics',
            name='like_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
