# Generated by Django 4.2.6 on 2024-02-28 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_app', '0008_remove_poststatistics_view_count_alter_post_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poststatistics',
            name='comment_count',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to='social_media_app.comment'),
        ),
        migrations.AlterField(
            model_name='poststatistics',
            name='like_count',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_likes', to='social_media_app.like'),
        ),
    ]
