# Generated by Django 4.2.6 on 2024-02-28 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_app', '0009_alter_poststatistics_comment_count_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
